plugins {
    id 'java-library'
}
apply plugin: 'kotlin'


configurations.implementation {
    exclude group: "org.jetbrains", module: "annotations"
}

dependencies {
    implementation project(path: ":javac")
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}


