
plugins {
    id 'com.android.application'  
}

android {
    namespace 'com.star4droid.star2d.evo'
    compileSdk 36
    buildToolsVersion '36.0.0'
    lint {
    disable 'MissingTranslation', 'TypographyFractions'
    checkOnly 'NewApi', 'HandlerLeak'
    abortOnError false
    checkReleaseBuilds false
    }
    testOptions {
        unitTests.all {
            enabled = false
        }
    }
    signingConfigs {
        release {
            def keystorePath = System.getenv("KEYSTORE_FILE") ?: "Star4droid.jks"
            def keystoreFile = file(keystorePath)
            if (keystoreFile.exists()) {
                storeFile keystoreFile
                storePassword System.getenv("KEYSTORE_PASSWORD")
                keyAlias System.getenv("KEY_ALIAS")
                keyPassword System.getenv("KEYSTORE_PASSWORD")
            } else {
                println "Release keystore '${keystoreFile.absolutePath}' not found. Using debug keystore."
                initWith signingConfigs.debug
            }
        }
    }
    defaultConfig {
        applicationId "com.star4droid.star2d.evo"
        minSdk 26
        targetSdk 36
        versionCode 46
        versionName "0.4.6Beta"
        externalNativeBuild {
            cmake {
                arguments "-DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON"
            }
        }
        vectorDrawables { 
            useSupportLibrary true
        }
    }

    packagingOptions {
        pickFirst '**/Messages_zh_CN.properties'
        pickFirst '**/Messages_zh_TW.properties'
        pickFirst '**/Messages_ja.properties'
        pickFirst '**/Messages.properties'
        pickFirst '**/Bundle.properties'
        exclude 'org/eclipse/jdt/internal/compiler/parser/parser13.rsc'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/ASL2.0'
        exclude("META-INF/*.kotlin_module") 
        pickFirst 'build-data.properties'
        pickFirst 'LICENSE'
        pickFirst 'sun/**/*.class'
        pickFirst 'com/sun/**/*.class'
        pickFirst 'org/jetbrains/**/*.class'
        pickFirst 'org/intellij/**/*.class'
        pickFirst 'org/apache/http/**/*.class'
        pickFirst 'net/lingala/zip4j/**/*.class'
        pickFirst 'org/apache/commons/codec/**/*.class'
        pickFirst 'javax/lang/model/**/*.class'
        pickFirst 'META-INF/**'
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    if (file("google-services.json").exists()) {
        apply plugin: 'com.google.gms.google-services'
        apply plugin: 'com.google.firebase.crashlytics'
    }

    buildFeatures {
        buildConfig true
    }
    
}

ext {
    gdxVersion = '1.13.1'
}

configurations { 
    natives 
    all {
        exclude group: 'com.intellij', module: 'annotations'
    }
}

dependencies {

    implementation("com.google.android.material:material:1.11.0")
    implementation project(':Formatter')
    implementation 'com.android.billingclient:billing:8.0.0'
    implementation("androidx.constraintlayout:constraintlayout:2.1.4")
    implementation("androidx.appcompat:appcompat:1.6.1")
    implementation fileTree(dir: 'libs', include: ['*.jar']);
    implementation fileTree(dir: 'libs', include: ['*.aar']);
    implementation files('../codeassist-libs/build-logic/libs/ecj.jar')
    implementation 'com.github.bumptech.glide:glide:4.16.0'
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation 'com.google.guava:guava:32.0.1-android'
  //  implementation 'com.google.guava:guava:guava-33.4.0-jre'
    implementation 'com.android.tools:r8:8.1.56'
    implementation platform("io.github.Rosemoe.sora-editor:bom:0.23.6")
    implementation "io.github.Rosemoe.sora-editor:editor"
    implementation "io.github.Rosemoe.sora-editor:language-textmate"
    implementation "io.github.Rosemoe.sora-editor:language-java"
    implementation 'com.badlogicgames.gdx:gdx:$gdxVersion'
    implementation "com.badlogicgames.gdx:gdx-freetype:$gdxVersion"
    
    natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-arm64-v8a"
    natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-armeabi-v7a"
    natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-x86"
    natives "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-x86_64"
    natives "com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion:natives-armeabi-v7a"
    natives "com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion:natives-arm64-v8a"
    natives "com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion:natives-x86"
    natives "com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion:natives-x86_64"
    natives "com.badlogicgames.gdx:gdx-freetype-platform:$gdxVersion:natives-armeabi-v7a"
    natives "com.badlogicgames.gdx:gdx-freetype-platform:$gdxVersion:natives-arm64-v8a"
    natives "com.badlogicgames.gdx:gdx-freetype-platform:$gdxVersion:natives-x86"
    natives "com.badlogicgames.gdx:gdx-freetype-platform:$gdxVersion:natives-x86_64"

    
    testImplementation 'com.badlogicgames.gdx:gdx-platform:$gdxVersion'
    // https://mvnrepository.com/artifact/com.badlogicgames.gdx/gdx-backend-lwjgl
    testImplementation 'com.badlogicgames.gdx:gdx-backend-lwjgl:$gdxVersion'
    // https://mvnrepository.com/artifact/com.badlogicgames.gdx/gdx-backend-android
    implementation 'com.badlogicgames.gdx:gdx-backend-android:1.13.0'
    // https://mvnrepository.com/artifact/com.badlogicgames.gdx/gdx-box2d
    implementation 'com.badlogicgames.gdx:gdx-box2d:1.13.0'
    // https://mvnrepository.com/artifact/com.badlogicgames.gdx/gdx-box2d-platform
    testImplementation 'com.badlogicgames.gdx:gdx-box2d-platform:$gdxVersion'
    constraints {
        implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.0") {
            because("kotlin-stdlib-jdk7 is now a part of kotlin-stdlib")
        }
        implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.0") {
            because("kotlin-stdlib-jdk8 is now a part of kotlin-stdlib")
        }
    }
// https://mvnrepository.com/artifact/com.badlogicgames.gdx/gdx-box2d
    implementation 'com.badlogicgames.gdx:gdx-box2d:$gdxVersion'
    
    implementation(platform("com.google.firebase:firebase-bom:34.3.0"))

    implementation("com.google.firebase:firebase-crashlytics-ndk")
    implementation("com.google.firebase:firebase-analytics")


    // CodeAssist Dependencies
    implementation project(path: ':code-editor')
    implementation project(path: ':xml-completion')
    implementation project(path: ':viewbinding-inject')
    implementation project(path: ':xml-repository')
    implementation project(path: ':java-completion')
    // not used for compilation, but for analysis
    implementation project(path: ':javac')

    implementation project(path: ':language-api')

    implementation project(path: ':build-logic')
    implementation project(path: ':manifmerger')
    implementation project(path: ':project')
    implementation project(path: ':logging')
    implementation project(path: ':jaxp')
    implementation project(path: ':common')
    implementation project(path: ':apksigner')
    implementation project(path: ':kotlin-completion')
    
    implementation project(path: ':dependency-resolver')

    implementation project(path: ':treeview')

    // apis
    implementation project(path: ':completion-api')
    implementation project(path: ':actions-api')
    implementation project(path: ':editor-api')
    implementation project(path: ':fileeditor-api')

    // formatters    
    implementation project(path: ':google-java-format')
    implementation project(path: ':ktfmt')
    
    // External dependencies required by CodeAssist
    implementation 'com.github.daniel-stoneuk:material-about-library:3.1.2'
    implementation 'com.github.angads25:filepicker:1.1.1'
    implementation 'androidx.preference:preference:1.2.1'
    implementation 'com.github.TutorialsAndroid:crashx:6.0.19'
    implementation 'org.slf4j:slf4j-api:2.0.16'
    implementation 'com.blankj:utilcodex:1.31.1'
    implementation 'org.jetbrains.kotlin:kotlin-stdlib:2.0.20'
    implementation 'org.antlr:antlr4-runtime:4.13.2'
    implementation 'commons-io:commons-io:2.16.1'

}

// Called every time gradle gets executed, takes the native dependencies of
// the natives configuration, and extracts them to the proper libs/ folders
// so they get packed with the APK.
tasks.register('copyAndroidNatives') {
    doFirst {
        file("libs/armeabi-v7a/").mkdirs()
        file("libs/arm64-v8a/").mkdirs()
        file("libs/x86_64/").mkdirs()
        file("libs/x86/").mkdirs()

        configurations.natives.copy().files.each { jar ->
            def outputDir = null
            if(jar.name.endsWith("natives-armeabi-v7a.jar")) outputDir = file("libs/armeabi-v7a")
            if(jar.name.endsWith("natives-arm64-v8a.jar")) outputDir = file("libs/arm64-v8a")
            if(jar.name.endsWith("natives-x86_64.jar")) outputDir = file("libs/x86_64")
            if(jar.name.endsWith("natives-x86.jar")) outputDir = file("libs/x86")
            if(outputDir != null) {
                copy {
                    from zipTree(jar)
                    into outputDir
                    include "*.so"
                }
            }
        }
    }
}

tasks.matching { it.name.contains("merge") && it.name.contains("JniLibFolders") }.configureEach { packageTask ->
    packageTask.dependsOn 'copyAndroidNatives'
}
